module Yclients
  class Configuration
    attr_reader partner_token: String
    attr_reader user_token: String?
    attr_reader base_url: String
    attr_reader timeout: Numeric
    attr_reader open_timeout: Numeric
    attr_reader logger: _Logger?

    def initialize: (partner_token: String, ?user_token: String?, ?base_url: String, ?timeout: Numeric, ?open_timeout: Numeric, ?logger: _Logger?) -> void
    def with_user_token: (String? value) -> instance
    def inspect: () -> String
  end

  class Client
    attr_reader configuration: Configuration

    def initialize: (partner_token: String, ?user_token: String?, ?base_url: String, ?timeout: Numeric, ?open_timeout: Numeric, ?logger: _Logger?, ?transport: _TransportFactory) -> void
    def with_user_token: (String? token) -> instance
    def inspect: () -> String

    def auth: () -> Resources::Auth
    def companies: () -> Resources::Companies
    def clients: () -> Resources::Clients
    def records: () -> Resources::Records
    def services: () -> Resources::Services
    def staff: () -> Resources::Staff
    def permissions: () -> Resources::Permissions
  end
end
